export {
  FACE_SIMILARITY_THRESHOLD,
  FACE_REGISTER_MIN_PHOTOS,
  FACE_REGISTER_MAX_PHOTOS,
  FACE_DETECTION_CONFIDENCE_THRESHOLD,
  FACE_DETECTION_MIN_FACE_SIZE,
  FACE_CROP_PADDING,
  MODEL_PATH,
} from './constants'
